# ----
# Site

title: Electra Guidelines
url: "https://electra-project.github.io/contribution-guidelines"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo:
description: Electra Contribution Guidelines for developers & contributors.
author:
  name: Electra Project
  email: coordinators@electraproject.org
  twitter: ElectracoinECA
social:
  name: Electra Project
  links:
    - https://electraproject.org
    - https://github.com/Electra-project

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

# https://blog.github.com/2017-11-29-use-any-theme-with-github-pages/
remote_theme: CloudCannon/edition-jekyll-template
